apiVersion: apps/v1
kind: Deployment
metadata:
  name: weapons-app-deployment
  labels:
    app: weapons-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weapons-app
  template:
    metadata:
      labels:
        app: weapons-app
    spec:
      containers:
      - name: weapons-app
        image: dannygoldberg/weapons-app:v1
        env:
        - name: HOST
        - value: "mysql-svc"
        ports:
        - containerPort: 8000